# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadFileModel',
        ),
    ]
